# Generated by Django 6.1.1 on 2026-09-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AHPDryLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('A', 'A Shift (06:00 - 14:00)'), ('B', 'B Shift (14:00 - 22:00)'), ('C', 'C Shift (22:00 - 06:00)'), ('G', 'General Shift')], max_length=1)),
                ('document_no', models.CharField(default='ADTPS/AHP/OPN/F/01', max_length=30)),
                ('ic1_initial', models.FloatField(blank=True, null=True, verbose_name='I/C-1 (AXC) Initial Reading')),
                ('ic1_final', models.FloatField(blank=True, null=True, verbose_name='I/C-1 (AXC) Final Reading')),
                ('ic2_initial', models.FloatField(blank=True, null=True, verbose_name='I/C-2 (AXD) Initial Reading')),
                ('ic2_final', models.FloatField(blank=True, null=True, verbose_name='I/C-2 (AXD) Final Reading')),
                ('fine_ash_silo_level', models.FloatField(blank=True, null=True, verbose_name='Fine Ash Silo Level (%)')),
                ('coarse_ash_silo_level', models.FloatField(blank=True, null=True, verbose_name='Coarse Ash Silo Level (%)')),
                ('mt300_ash_silo_level', models.FloatField(blank=True, null=True, verbose_name='300 MT Ash Silo Level (%)')),
                ('fly_ash_quantity', models.FloatField(blank=True, null=True, verbose_name='Fly Ash Quantity (MT)')),
                ('observations', models.TextField(blank=True, verbose_name='Details of Observation/Action Taken')),
                ('remarks', models.TextField(blank=True)),
                ('operator_signature', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('approval_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ahp_dry_log_entries',
                'ordering': ['-date', 'shift'],
            },
        ),
        migrations.CreateModel(
            name='AHPWetLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('A', 'A Shift (06:00 - 14:00)'), ('B', 'B Shift (14:00 - 22:00)'), ('C', 'C Shift (22:00 - 06:00)'), ('G', 'General Shift')], max_length=1)),
                ('document_no', models.CharField(default='ADTPS/AHP/OPN/F/02', max_length=30)),
                ('unit1_load', models.FloatField(blank=True, null=True, verbose_name='Unit-1 Load (MW)')),
                ('unit1_coal_flow', models.FloatField(blank=True, null=True, verbose_name='Unit-1 Coal Flow (T/hr)')),
                ('unit2_load', models.FloatField(blank=True, null=True, verbose_name='Unit-2 Load (MW)')),
                ('unit2_coal_flow', models.FloatField(blank=True, null=True, verbose_name='Unit-2 Coal Flow (T/hr)')),
                ('u1_esp_fields_discharged', models.CharField(blank=True, max_length=100)),
                ('u1_esp_hopper_level_hi', models.CharField(blank=True, max_length=100)),
                ('u1_esp_cerm_avail', models.CharField(blank=True, max_length=50)),
                ('u1_esp_eerm_avail', models.CharField(blank=True, max_length=50)),
                ('incomer_osa_initial', models.FloatField(blank=True, null=True)),
                ('incomer_osa_final', models.FloatField(blank=True, null=True)),
                ('incomer_osc_initial', models.FloatField(blank=True, null=True)),
                ('incomer_osc_final', models.FloatField(blank=True, null=True)),
                ('ahp_lighting_initial', models.FloatField(blank=True, null=True)),
                ('ahp_lighting_final', models.FloatField(blank=True, null=True)),
                ('grand_total_kwh', models.FloatField(blank=True, null=True)),
                ('u1_ba_start', models.TimeField(blank=True, null=True)),
                ('u1_ba_stop', models.TimeField(blank=True, null=True)),
                ('u1_ba_total_time', models.FloatField(blank=True, null=True)),
                ('u2_ba_start', models.TimeField(blank=True, null=True)),
                ('u2_ba_stop', models.TimeField(blank=True, null=True)),
                ('u2_ba_total_time', models.FloatField(blank=True, null=True)),
                ('events_remarks', models.TextField(blank=True)),
                ('follow_up', models.TextField(blank=True)),
                ('protection_bypassed', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('approval_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ahp_wet_log_entries',
                'ordering': ['-date', 'shift'],
            },
        ),
        migrations.CreateModel(
            name='DryEquipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(choices=[('COMP-1', 'Compressor No-1'), ('COMP-2', 'Compressor No-2'), ('COMP-3', 'Compressor No-3'), ('COMP-4', 'Compressor No-4'), ('CT-FAN', 'Cooling Tower Fan'), ('CT-PUMP-A', 'Cooling Tower Pump-A'), ('CT-PUMP-B', 'Cooling Tower Pump-B'), ('CLASS-A', 'Classifier-A'), ('CLASS-B', 'Classifier-B')], max_length=20)),
                ('cycle', models.IntegerField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('stop_time', models.TimeField(blank=True, null=True)),
                ('running_hrs', models.FloatField(blank=True, null=True)),
                ('availability_status', models.CharField(blank=True, choices=[('R', 'Running'), ('A', 'Available'), ('B', 'Breakdown'), ('P', 'PTW (Permit to Work)')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'ahp_dry_equipment_status',
            },
        ),
        migrations.CreateModel(
            name='ESPDryDeashing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('1', 'Unit 1'), ('2', 'Unit 2')], max_length=1)),
                ('esp_pass', models.CharField(choices=[('AB-1', 'AB-1st Field'), ('CD-1', 'CD-1st Field'), ('AB-2', 'AB-2nd Field'), ('CD-2', 'CD-2nd Field'), ('AB-3', 'AB-3rd Field'), ('CD-3', 'CD-3rd Field'), ('AB-4', 'AB-4th Field'), ('CD-4', 'CD-4th Field'), ('AB-5', 'AB-5th Field'), ('CD-5', 'CD-5th Field'), ('AB-6', 'AB-6th Field'), ('CD-6', 'CD-6th Field')], max_length=5)),
                ('cycle', models.IntegerField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('stop_time', models.TimeField(blank=True, null=True)),
                ('total_time', models.FloatField(blank=True, null=True, verbose_name='Total Time (hrs)')),
            ],
            options={
                'db_table': 'ahp_esp_dry_deashing',
                'ordering': ['unit', 'esp_pass', 'cycle'],
            },
        ),
        migrations.CreateModel(
            name='ESPFieldAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('1', 'Unit 1'), ('2', 'Unit 2')], max_length=1)),
                ('field', models.CharField(choices=[('AB-1', 'AB-1st'), ('CD-1', 'CD-1st'), ('AB-2', 'AB-2nd'), ('CD-2', 'CD-2nd'), ('AB-3', 'AB-3rd'), ('CD-3', 'CD-3rd'), ('AB-4', 'AB-4th'), ('CD-4', 'CD-4th'), ('AB-5', 'AB-5th'), ('CD-5', 'CD-5th'), ('AB-6', 'AB-6th'), ('CD-6', 'CD-6th'), ('ECO-1-4', 'ECO 1-4'), ('APH-1-3', 'APH 1-3'), ('APH-4-6', 'APH 4-6'), ('DUCT-E', 'Duct-East'), ('DUCT-W', 'Duct-West'), ('CA-SILO', 'C.A. Silo')], max_length=10)),
                ('avail_status', models.CharField(blank=True, choices=[('R', 'Running'), ('A', 'Available'), ('B', 'Breakdown'), ('P', 'PTW (Permit to Work)')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'ahp_esp_field_availability',
            },
        ),
        migrations.CreateModel(
            name='ESPWetDeashing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('1', 'Unit 1'), ('2', 'Unit 2')], max_length=1)),
                ('component', models.CharField(choices=[('AB-1', 'AB-1st Field'), ('CD-1', 'CD-1st Field'), ('AB-2', 'AB-2nd Field'), ('CD-2', 'CD-2nd Field'), ('AB-3', 'AB-3rd Field'), ('CD-3', 'CD-3rd Field'), ('AB-4', 'AB-4th Field'), ('CD-4', 'CD-4th Field'), ('AB-5', 'AB-5th Field'), ('CD-5', 'CD-5th Field'), ('AB-6', 'AB-6th Field'), ('CD-6', 'CD-6th Field'), ('ECO-1-4', 'Economiser 1 to 4'), ('APH-1-3', 'Air Pre Heater 1 to 3'), ('APH-4-6', 'Air Pre Heater 4 to 6'), ('DUCT-W', 'Duct-West'), ('DUCT-E', 'Duct-East'), ('CAS', 'Coarse Ash Silo')], max_length=10)),
                ('cycle', models.IntegerField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('stop_time', models.TimeField(blank=True, null=True)),
                ('total_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ahp_esp_wet_deashing',
            },
        ),
        migrations.CreateModel(
            name='LogbookAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('dry', 'Dry System'), ('wet', 'Wet System')], max_length=5)),
                ('file', models.FileField(upload_to='ahp_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ahp_attachments',
            },
        ),
        migrations.CreateModel(
            name='WetEquipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump', models.CharField(choices=[('ADP-A', 'ADP-A'), ('ADP-B', 'ADP-B'), ('ADP-C', 'ADP-C'), ('ADP-D', 'ADP-D'), ('HPP-A', 'HPP-A'), ('HPP-B', 'HPP-B'), ('HPP-C', 'HPP-C'), ('SWP-A', 'SWP-A'), ('SWP-B', 'SWP-B'), ('ISP-1A', 'ISP-1A'), ('ISP-2A', 'ISP-2A'), ('ISP-2B', 'ISP-2B'), ('LPP-A', 'LPP-A'), ('LPP-B', 'LPP-B')], max_length=10)),
                ('cycle', models.IntegerField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('stop_time', models.TimeField(blank=True, null=True)),
                ('running_hrs', models.FloatField(blank=True, null=True)),
                ('avail_status', models.CharField(blank=True, choices=[('R', 'Running'), ('A', 'Available'), ('B', 'Breakdown'), ('P', 'PTW (Permit to Work)')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'ahp_wet_equipment_status',
            },
        ),
    ]
