# Generated by Django 6.1.1 on 2026-09-22 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ahp_logbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ahpdrylogentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dry_logs_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ahpdrylogentry',
            name='field_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dry_logs_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ahpdrylogentry',
            name='prepared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dry_logs_prepared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ahpdrylogentry',
            name='shift_incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dry_logs_incharge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ahpwetlogentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wet_logs_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ahpwetlogentry',
            name='prepared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wet_logs_prepared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dryequipmentstatus',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_status', to='ahp_logbook.ahpdrylogentry'),
        ),
        migrations.AddField(
            model_name='espdrydeashing',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esp_dry_deashing', to='ahp_logbook.ahpdrylogentry'),
        ),
        migrations.AddField(
            model_name='espfieldavailability',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esp_field_availability', to='ahp_logbook.ahpwetlogentry'),
        ),
        migrations.AddField(
            model_name='espwetdeashing',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esp_wet_deashing', to='ahp_logbook.ahpwetlogentry'),
        ),
        migrations.AddField(
            model_name='logbookattachment',
            name='dry_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ahp_logbook.ahpdrylogentry'),
        ),
        migrations.AddField(
            model_name='logbookattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logbookattachment',
            name='wet_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ahp_logbook.ahpwetlogentry'),
        ),
        migrations.AddField(
            model_name='wetequipmentstatus',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_status', to='ahp_logbook.ahpwetlogentry'),
        ),
        migrations.AlterUniqueTogether(
            name='ahpdrylogentry',
            unique_together={('date', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='ahpwetlogentry',
            unique_together={('date', 'shift')},
        ),
    ]
