# Generated by Django 5.2.17 on 2026-09-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahp_logbook', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahpwetlogentry',
            name='u2_esp_cerm_avail',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ahpwetlogentry',
            name='u2_esp_eerm_avail',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ahpwetlogentry',
            name='u2_esp_fields_discharged',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ahpwetlogentry',
            name='u2_esp_hopper_level_hi',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
