# Generated by Django 5.2.17 on 2026-09-29 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahp_logbook', '0003_add_unit2_esp_status_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('dry', 'Dry System'), ('wet', 'Wet System')], max_length=5)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='archived_logbooks/')),
                ('version', models.IntegerField(default=1)),
                ('entry_date', models.DateField()),
                ('entry_shift', models.CharField(choices=[('A', 'A Shift (06:00 - 14:00)'), ('B', 'B Shift (14:00 - 22:00)'), ('C', 'C Shift (22:00 - 06:00)'), ('G', 'General Shift')], max_length=1)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('retention_until', models.DateField(blank=True, help_text='Date until which to retain', null=True)),
                ('snapshot_data', models.JSONField(blank=True, help_text='JSON snapshot of entry at archive time', null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dry_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='ahp_logbook.ahpdrylogentry')),
                ('wet_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='ahp_logbook.ahpwetlogentry')),
            ],
            options={
                'db_table': 'archived_logbooks',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('outgoing_shift', models.CharField(choices=[('A', 'A Shift (06:00 - 14:00)'), ('B', 'B Shift (14:00 - 22:00)'), ('C', 'C Shift (22:00 - 06:00)'), ('G', 'General Shift')], max_length=1)),
                ('incoming_shift', models.CharField(choices=[('A', 'A Shift (06:00 - 14:00)'), ('B', 'B Shift (14:00 - 22:00)'), ('C', 'C Shift (22:00 - 06:00)'), ('G', 'General Shift')], max_length=1)),
                ('summary', models.TextField(help_text='Summary of shift activities')),
                ('pending_items', models.TextField(blank=True, help_text='Pending items for next shift')),
                ('critical_observations', models.TextField(blank=True, help_text='Critical observations to carry forward')),
                ('equipment_issues', models.TextField(blank=True, help_text='Equipment issues or concerns')),
                ('safety_concerns', models.TextField(blank=True, help_text='Safety related concerns')),
                ('handover_notes', models.TextField(blank=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dry_log_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='ahp_logbook.ahpdrylogentry')),
                ('incoming_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handovers_received', to=settings.AUTH_USER_MODEL)),
                ('outgoing_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_given', to=settings.AUTH_USER_MODEL)),
                ('wet_log_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='ahp_logbook.ahpwetlogentry')),
            ],
            options={
                'db_table': 'shift_handovers',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('unit', models.CharField(choices=[('1', 'Unit 1'), ('2', 'Unit 2'), ('common', 'Common')], max_length=10)),
                ('department', models.CharField(choices=[('ahp', 'Ash Handling'), ('operations', 'Operations'), ('electrical', 'Electrical'), ('mechanical', 'Mechanical'), ('ci', 'C&I'), ('chp', 'CHP')], default='ahp', max_length=20)),
                ('category', models.CharField(choices=[('abnormality', 'Plant Abnormality'), ('unit_trip', 'Unit Trip'), ('breakdown', 'Equipment Breakdown'), ('safety', 'Safety Incident'), ('near_miss', 'Near Miss'), ('environmental', 'Environmental Observation'), ('instruction', 'Operational Instruction'), ('maintenance', 'Maintenance Activity')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('equipment_tag', models.CharField(blank=True, help_text='Equipment identifier', max_length=100)),
                ('action_taken', models.TextField(blank=True)),
                ('event_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dry_log_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ahp_logbook.ahpdrylogentry')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_events', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_events', to=settings.AUTH_USER_MODEL)),
                ('wet_log_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ahp_logbook.ahpwetlogentry')),
            ],
            options={
                'db_table': 'event_records',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['category', '-date'], name='event_recor_categor_1b87ab_idx'), models.Index(fields=['severity', 'event_status'], name='event_recor_severit_93bf37_idx'), models.Index(fields=['department', '-date'], name='event_recor_departm_a6aa39_idx')],
            },
        ),
    ]
