# Generated by Django 5.2.17 on 2026-09-29 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('submit', 'Submitted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('login', 'Logged In'), ('logout', 'Logged Out'), ('password_change', 'Password Changed'), ('export', 'Data Exported'), ('handover', 'Shift Handover')], max_length=20)),
                ('model_name', models.CharField(blank=True, help_text='e.g. AHPDryLogEntry', max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of object', max_length=300)),
                ('old_values', models.JSONField(blank=True, help_text='Previous field values', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Updated field values', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('extra_info', models.TextField(blank=True, help_text='Additional context or remarks')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_logs_user_id_e11c73_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_logs_model_n_656046_idx'), models.Index(fields=['action', '-timestamp'], name='audit_logs_action_f48619_idx')],
            },
        ),
    ]
